### ISSUE TITLE
The directory is not empty: Exception

### ISSUE THREAD

**Issue by DarkneSsDz** [NickstaDB/patch-apk#37] opened 2022-08-12 18:01 UTC
[https://i.imgur.com/SEiwzYP.png](url)

any help would be very appreciated from the coder

**Comment by NickstaDB** [comment] 2022-08-19 09:08
The first exception is an issue with running `apktool.bat` on Windows. The second exception is caused by a known Python bug that occurs intermittently on Windows (https://bugs.python.org/issue29982).

I've pushed a fix for the first exception. Closing this for now but feel free to comment/reopen if it doesn't fix the issue.

**Closed by NickstaDB** 2022-08-19 09:08 UTC
